server {
    listen 80;
    server_name api.local;

    location / {
        proxy_pass http://127.0.0.1:3000;
        auth_request /oauth2/validate;
    }

    location = /oauth2/validate {
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Authorization $http_authorization;
        proxy_pass https://192.168.43.221:9443/oauth2/introspect;
        proxy_ssl_verify off;
    }
}